---
- name: "Install apache avec Docker"
  hosts: prod
  become: true
  vars:
    ansible_sudo_pass: admin
  pre_tasks:
    - name: Install EPEL repo
      package: name=epel-release state=present
      when: ansible_distribution == "CentOS"
    - name: download pip script
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py
    - name: install python-pip
      command: python2.7 /tmp/get-pip.py
    - name: Install Docker Python
      pip: name=docker-py
  tasks:
    - name: install software
      yum:
        name: ['wget', 'git']
        state: present
      when: ansible_distribution == 'CentOS'
    - name:  Copy website file template
      template:
        src: ./template/index.html.j2
        dest: /home/admin/index.html
    - name: Creer un container apache
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
        volumes:
          - /home/admin/index.html:/usr/local/apache2/htdocs/index.html
